### ISSUE TITLE
Not showing any beat maps on the website

### ISSUE THREAD

**Issue by ijustgottheworldsmostsmalliphone** [WebOsu-2/webosu-2.github.io#12] opened 2024-08-20 10:09 UTC
![Screenshot 2024-08-20 6 09 09 PM](https://github.com/user-attachments/assets/6817d652-6bc6-494d-af72-3fcfceddb608)

**Comment by Mostlime12195** [comment] 2024-09-20 19:37
I have made several large changes, please check to see if it works now.

**Comment by Mostlime12195** [comment] 2024-09-23 15:38
I apologise, but I will have to close this because I am not able to reproduce this issue, and you do not seem to be replying to my comments. Re-open this issue if anyone else has this issue.

**Closed** 2024-09-23 15:38 UTC
